import {
  defaultFileUploadMaxBytes,
  SetupAuthCookieSameSite,
  SetupAuthCookieSecure,
  SetupBoolean,
  SetupCacheStore,
  SetupDatabaseDialect,
  SetupEmailVerificationService,
  SetupFileStorageDriver,
  SetupLogTarget,
  SetupNodeEnv,
  SetupSmsVerificationService,
} from '@tilty/shared/setup';

import { type SetupEnvironment } from './setup-environment';

export const developmentAuthTokenSecret = 'development-auth-token-secret-change-before-production';
export const defaultFrontendOrigin = 'http://localhost:8011';
export const defaultCorsOrigins = defaultFrontendOrigin;
export const defaultSsoFrontendCallbackUrl = `${defaultFrontendOrigin}/login`;
export const defaultSsoScopes = 'openid profile email';

export const defaultSetupEnvironment = {
  NODE_ENV: SetupNodeEnv.Development,
  SERVER_HOST: '0.0.0.0',
  SERVER_PORT: '3000',
  APP_DOMAIN: defaultFrontendOrigin,
  APP_CORS_ORIGINS: defaultCorsOrigins,
  APP_CSP_RESOURCE_ORIGINS: '*',
  SERVER_TRUST_PROXY: SetupBoolean.False,
  SERVER_MULTI_INSTANCE_ENABLED: SetupBoolean.False,
  DATABASE_DIALECT: SetupDatabaseDialect.Sqlite,
  DATABASE_STORAGE: './data/database.sqlite',
  DATABASE_URL: '',
  DATABASE_SSL: SetupBoolean.False,
  DATABASE_CONNECT_TIMEOUT_MS: '10000',
  DATABASE_POOL_MAX: '10',
  DATABASE_POOL_MIN: '0',
  DATABASE_POOL_ACQUIRE_MS: '30000',
  DATABASE_POOL_IDLE_MS: '10000',
  CACHE_STORE: SetupCacheStore.Memory,
  CACHE_REDIS_URL: 'redis://localhost:6379/0',
  CACHE_REDIS_REQUEST_TIMEOUT_MS: '10000',
  FILE_STORAGE_DRIVER: SetupFileStorageDriver.Local,
  FILE_UPLOAD_MAX_BYTES: String(defaultFileUploadMaxBytes),
  FILE_PUBLIC_BASE_URL: '/uploads',
  FILE_LOCAL_ROOT: './data/uploads',
  FILE_OSS_ACCESS_KEY_ID: '',
  FILE_OSS_ACCESS_KEY_SECRET: '',
  FILE_OSS_BUCKET: '',
  FILE_OSS_ENDPOINT: '',
  FILE_OSS_REGION: '',
  FILE_OSS_PUBLIC_BASE_URL: '',
  SCHEDULER_ENABLED: SetupBoolean.True,
  SCHEDULER_LOCK_TTL_MS: '300000',
  AUTH_TOKEN_SECRET: '',
  AUTH_ACCESS_TOKEN_TTL_SECONDS: '900',
  AUTH_REFRESH_TOKEN_TTL_SECONDS: '2592000',
  AUTH_VERIFICATION_CHALLENGE_TTL_SECONDS: '300',
  AUTH_VERIFICATION_MAX_ATTEMPTS: '5',
  AUTH_VERIFICATION_SUDO_TTL_SECONDS: '900',
  AUTH_PASSKEY_RP_NAME: 'Tilty Scaffold',
  AUTH_PASSKEY_REGISTRATION_TTL_SECONDS: '300',
  AUTH_PASSKEY_OPERATION_TIMEOUT_MS: '60000',
  AUTH_TOTP_ISSUER: 'Tilty Scaffold',
  AUTH_TOTP_SETUP_TTL_SECONDS: '600',
  AUTH_ACCESS_TOKEN_COOKIE_NAME: 'tilty_scaffold_access_token',
  AUTH_REFRESH_TOKEN_COOKIE_NAME: 'tilty_scaffold_refresh_token',
  AUTH_COOKIE_SAME_SITE: SetupAuthCookieSameSite.Lax,
  AUTH_COOKIE_SECURE: SetupAuthCookieSecure.Auto,
  AUTH_RATE_LIMIT_WINDOW_MS: '60000',
  AUTH_RATE_LIMIT_MAX: '10',
  GLOBAL_RATE_LIMIT_WINDOW_MS: '60000',
  GLOBAL_RATE_LIMIT_MAX: '1000',
  LOG_REQUEST_ENABLED: SetupBoolean.True,
  LOG_TARGETS: SetupLogTarget.Console,
  LOG_PENDING_WRITE_MAX: '1000',
  LOG_WRITE_TIMEOUT_MS: '5000',
  LOG_LOCAL_PATH: './logs/backend.log',
  LOG_SLS_ENDPOINT: '',
  LOG_SLS_PROJECT: '',
  LOG_SLS_LOGSTORE: '',
  LOG_SLS_ACCESS_KEY_ID: '',
  LOG_SLS_ACCESS_KEY_SECRET: '',
  LOG_SLS_TOPIC: 'tilty-scaffold',
  LOG_SLS_SOURCE: 'backend',
  EMAIL_VERIFICATION_SERVICE: SetupEmailVerificationService.Off,
  EMAIL_VERIFICATION_CODE_EXPIRES_IN_MS: '600000',
  EMAIL_VERIFICATION_CODE_COOLDOWN_MS: '60000',
  EMAIL_SMTP_PROFILES: '[]',
  SMS_VERIFICATION_SERVICE: SetupSmsVerificationService.Off,
  SMS_VERIFICATION_CODE_EXPIRES_IN_MS: '600000',
  SMS_VERIFICATION_CODE_COOLDOWN_MS: '60000',
  SMS_ALICLOUD_PROFILES: '[]',
  SSO_ENABLED: SetupBoolean.False,
  SSO_PROFILES: '[]',
} as const satisfies SetupEnvironment;

export const defaultSetupRuntimeEnvironment = {
  APP_DOMAIN: defaultSetupEnvironment.APP_DOMAIN,
  APP_CSP_RESOURCE_ORIGINS: defaultSetupEnvironment.APP_CSP_RESOURCE_ORIGINS,
  GLOBAL_RATE_LIMIT_MAX: defaultSetupEnvironment.GLOBAL_RATE_LIMIT_MAX,
  GLOBAL_RATE_LIMIT_WINDOW_MS: defaultSetupEnvironment.GLOBAL_RATE_LIMIT_WINDOW_MS,
  LOG_PENDING_WRITE_MAX: defaultSetupEnvironment.LOG_PENDING_WRITE_MAX,
  LOG_REQUEST_ENABLED: defaultSetupEnvironment.LOG_REQUEST_ENABLED,
  LOG_TARGETS: defaultSetupEnvironment.LOG_TARGETS,
  LOG_WRITE_TIMEOUT_MS: defaultSetupEnvironment.LOG_WRITE_TIMEOUT_MS,
  SERVER_HOST: '127.0.0.1',
  SERVER_PORT: defaultSetupEnvironment.SERVER_PORT,
  SERVER_TRUST_PROXY: defaultSetupEnvironment.SERVER_TRUST_PROXY,
} as const;
